apiVersion: v1
kind: Service
metadata:
  name: ethereum-load-balancer
spec:
  selector:
    app: ethereum-node
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
  type: LoadBalancer
