apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethereum-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/ethereum/storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
